-- ═══════════════════════════════════════════════════════════════════════════════
-- SENTIX PRO - SIGNAL ENGINE v4.0 UPGRADE
-- Migration: v4.0 - Multi-timeframe, trade levels, derivatives data
-- Run this in Supabase SQL Editor: https://supabase.com > SQL Editor > New Query
-- ═══════════════════════════════════════════════════════════════════════════════

-- ─── 1. ADD NEW JSONB COLUMNS TO SIGNALS TABLE ────────────────────────────────

-- Trade levels: entry, stopLoss, takeProfit1, takeProfit2, riskRewardRatio
ALTER TABLE signals
  ADD COLUMN IF NOT EXISTS trade_levels JSONB DEFAULT NULL;

-- Derivatives data: fundingRate, openInterest, longShortRatio, sentiment
ALTER TABLE signals
  ADD COLUMN IF NOT EXISTS derivatives JSONB DEFAULT NULL;

-- Multi-timeframe data: 4h, 1h, 15m signals + confluence level
ALTER TABLE signals
  ADD COLUMN IF NOT EXISTS timeframes JSONB DEFAULT NULL;

-- Update interval_tf default to 'multi' for multi-timeframe signals
ALTER TABLE signals
  ALTER COLUMN interval_tf SET DEFAULT 'multi';

-- ─── 2. INDEX FOR CONFLUENCE QUERIES ──────────────────────────────────────────

-- GIN index for querying inside JSONB (e.g. confluence level)
CREATE INDEX IF NOT EXISTS idx_signals_timeframes ON signals USING GIN (timeframes);

-- ═══════════════════════════════════════════════════════════════════════════════
-- MIGRATION COMPLETE
--
-- New columns on signals table:
--   - trade_levels (JSONB): Entry/SL/TP1/TP2/R:R for BUY/SELL signals
--   - derivatives (JSONB): Funding rate, OI, L/S ratio from Binance Futures
--   - timeframes (JSONB): Per-TF signals (4H/1H/15M) + confluence assessment
--
-- These columns are nullable - existing rows remain untouched.
-- New signals generated by v4.0 engine will populate them automatically.
-- ═══════════════════════════════════════════════════════════════════════════════
